### PR TITLE
Increase compatibility with other error handling libraries

### PR DESCRIPTION
**Pull request by Finomnis**
To be more specific, increase compatibility with:
- `Box<dyn std::error::Error>`
- [anyhow](https://crates.io/crates/anyhow)
- [miette](https://crates.io/crates/miette)

This is based on PR https://github.com/Finomnis/tokio-graceful-shutdown/pull/16, contributed by [calavera](https://github.com/calavera).

### CODE REVIEW

**Comment by Finomnis** [comment]
@calavera Here's my attempt .. what's your opinion?

**Comment by Finomnis** [comment]
I attempted to implement a minimal example for subsystems with miette based errors, but I keep stumbling across the problem that `miette::Report` is not convertible to `Box<dyn Error>`.

I opened a bug report for this problem here: https://github.com/zkat/miette/issues/146

**Review by calavera — COMMENTED** [review]
This is awesome, thanks for looking into it 🙌

**Comment by Finomnis** [comment]
Upstream patch on miette got merged, waiting for new miette release

**Pull request merged**
