### PR TITLE
Implement `Clone`, `Copy` for `NestedSubsystem`

### PR DESCRIPTION
**Pull request by 9999years**
Hello! Thanks for this library! I've added implementations of `Clone` and `Copy` for `NestedSubsystem`. This makes it easier to perform a partial shutdown.

### CODE REVIEW

**Comment by Finomnis** [comment]
Having `NestedSubsystem` not copy or clone is on purpose, so that `perform_partial_shutdown` cannot be called multiple times. Otherwise there might be weird race conditions.

If you have a better idea on how to deal with repeated requests to parial shutdowns of the same subsystem, feel free to suggest them.

The base problem here is that the internal implementation of this crate is questionable in hindsight. Especially everything surrounding partial shutdowns is kind of a dirty hack. I'm in the process of a complete rewrite which should simplify and improve things. Sadly, due to external complications that I have no control over, I currently have very little spare time. I'm trying to continue working on it whenever I can, but I cannot promise any deadlines right now.

While the problem this crate tries to solve sounds easy at first, it has a lot of hidden complications in the details. The two really hard topics here are error routing/handling and ownership (specifically preventing ownership cycles). I solved most of those problems in the rework already (theoretically, integration still pending), but it might still take some time.

**Comment by 9999years** [comment]
Hmm, yes, I did think the partial shutdown mechanism was a little weird. I think in practice you'd usually want partial _restarts_ rather than partial shutdowns on their own. (I'm reminded of the interesting system nested restarts that the Apollo Guidance Computer implemented that I learned about from [this fascinating talk by Robert Wills](https://www.youtube.com/watch?v=B1J2RMorJXM).)

I also really want a multiple stage shutdown mechanism, at least for my use-case: I want to do a graceful shutdown first, then if the user presses `Ctrl-C` again I want to do a hard shutdown (`SIGKILL` to child processes). I'm not sure if that's something you've thought of.

I could probably devote some time to helping fix this library up if you'd like — let me know.

**Comment by Finomnis** [comment]
I could give you viewing rights for my rework repository, to get some guidance on API design. I'm not sure if it's worth putting much effort into the existing code.

Let me know if that's something you are interested in.

**Comment by 9999years** [comment]
Sure, I'm definitely curious to look at it.

**Comment by Finomnis** [comment]
Do you have discord? If so, let's continue there. (

**Comment by Finomnis** [comment]
Accidentally pressed the reopen button on my phone.

**Pull request closed without merging**
